Add configuration to kernel via Kconfig, add credits to README.md

diff --git a/kernel/Makefile b/kernel/Makefile
--- a/kernel/Makefile
+++ b/kernel/Makefile
@@ -7,22 +7,90 @@ endif
 
 include config.mk
 
-SRC = $(wildcard io/*.c) $(wildcard io/*.S) $(wildcard main/*.c) $(wildcard main/*.S) $(wildcard mm/*.c) $(wildcard mm/*.S) $(wildcard syscalls/*.c) $(wildcard syscalls/*.S)
-OBJ = $(SRC:.c=.o)
-OBJ := $(OBJ:.S=.o)
-DEP := $(OBJ:.o=.d)
-
+SRC := $(wildcard io/*.c) $(wildcard io/*.S) $(wildcard main/*.c) $(wildcard main/*.S) $(wildcard mm/*.c) $(wildcard mm/*.S) $(wildcard syscalls/*.c) $(wildcard syscalls/*.S)
 UACPI_SRC = $(wildcard uacpi/source/*.c)
-UACPI_OBJ = $(patsubst uacpi/source/%.c,$(UACPI_BUILD)/%.o,$(UACPI_SRC))
+
+include Kconfig.mk
+
+OBJ := $(SRC:.c=.o)
+OBJ := $(OBJ:.S=.o)
+UACPI_OBJ = $(patsubst uacpi/source/%.c,uacpi/build/%.o,$(UACPI_SRC))
+
+DEP := $(OBJ:.o=.d)
 UACPI_DEP = $(UACPI_OBJ:.o=.d)
 
 SUBDIRS = main io mm syscalls
 
+-include $(DEP)
 -include $(UACPI_DEP)
 
 .DEFAULT_GOAL := all
 
 all: kernel
+
+menuconfig:
+	@$(MAKE) -C ../scripts/kconfig
+	@oldsum=$$(md5sum .config 2>/dev/null | cut -d' ' -f1); \
+	KCONFIG_CONFIG=.config ../scripts/kconfig/main/mconf Kconfig; \
+	ret=$$?; \
+	newsum=$$(md5sum .config 2>/dev/null | cut -d' ' -f1); \
+	if [ $$ret -ne 0 ]; then exit $$ret; fi; \
+	if [ -f .config ] && { [ "$$oldsum" != "$$newsum" ] || [ ! -f include/generated/autoconf.h ]; }; then \
+		rm -rf include/generated && mkdir -p include/generated && \
+		KCONFIG_CONFIG=.config KCONFIG_AUTOHEADER=include/generated/autoconf.h KCONFIG_AUTOCONFIG=include/generated/auto.conf KCONFIG_TRISTATE=include/generated/tristate.conf ../scripts/kconfig/main/conf --silentoldconfig Kconfig && \
+		find include/generated -mindepth 1 ! -name 'autoconf.h' -delete; \
+	fi
+
+allyesconfig:
+	@$(MAKE) -C ../scripts/kconfig
+	@KCONFIG_CONFIG=.config ../scripts/kconfig/main/conf --allyesconfig Kconfig && \
+	if [ -f .config ]; then \
+		rm -rf include/generated && mkdir -p include/generated && \
+		KCONFIG_CONFIG=.config KCONFIG_AUTOHEADER=include/generated/autoconf.h KCONFIG_AUTOCONFIG=include/generated/auto.conf KCONFIG_TRISTATE=include/generated/tristate.conf ../scripts/kconfig/main/conf --silentoldconfig Kconfig && \
+		find include/generated -mindepth 1 ! -name 'autoconf.h' -delete; \
+	fi
+
+allnoconfig:
+	@$(MAKE) -C ../scripts/kconfig
+	@KCONFIG_CONFIG=.config ../scripts/kconfig/main/conf --allnoconfig Kconfig && \
+	if [ -f .config ]; then \
+		rm -rf include/generated && mkdir -p include/generated && \
+		KCONFIG_CONFIG=.config KCONFIG_AUTOHEADER=include/generated/autoconf.h KCONFIG_AUTOCONFIG=include/generated/auto.conf KCONFIG_TRISTATE=include/generated/tristate.conf ../scripts/kconfig/main/conf --silentoldconfig Kconfig && \
+		find include/generated -mindepth 1 ! -name 'autoconf.h' -delete; \
+	fi
+
+alldefconfig:
+	@$(MAKE) -C ../scripts/kconfig
+	@KCONFIG_CONFIG=.config ../scripts/kconfig/main/conf --alldefconfig Kconfig && \
+	if [ -f .config ]; then \
+		rm -rf include/generated && mkdir -p include/generated && \
+		KCONFIG_CONFIG=.config KCONFIG_AUTOHEADER=include/generated/autoconf.h KCONFIG_AUTOCONFIG=include/generated/auto.conf KCONFIG_TRISTATE=include/generated/tristate.conf ../scripts/kconfig/main/conf --silentoldconfig Kconfig && \
+		find include/generated -mindepth 1 ! -name 'autoconf.h' -delete; \
+	fi
+
+defconfig: alldefconfig
+
+oldconfig:
+	@$(MAKE) -C ../scripts/kconfig
+	@KCONFIG_CONFIG=.config ../scripts/kconfig/main/conf --oldconfig Kconfig && \
+	if [ -f .config ]; then \
+		rm -rf include/generated && mkdir -p include/generated && \
+		KCONFIG_CONFIG=.config KCONFIG_AUTOHEADER=include/generated/autoconf.h KCONFIG_AUTOCONFIG=include/generated/auto.conf KCONFIG_TRISTATE=include/generated/tristate.conf ../scripts/kconfig/main/conf --silentoldconfig Kconfig && \
+		find include/generated -mindepth 1 ! -name 'autoconf.h' -delete; \
+	fi
+
+olddefconfig:
+	@$(MAKE) -C ../scripts/kconfig
+	@KCONFIG_CONFIG=.config ../scripts/kconfig/main/conf --olddefconfig Kconfig && \
+	if [ -f .config ]; then \
+		rm -rf include/generated && mkdir -p include/generated && \
+		KCONFIG_CONFIG=.config KCONFIG_AUTOHEADER=include/generated/autoconf.h KCONFIG_AUTOCONFIG=include/generated/auto.conf KCONFIG_TRISTATE=include/generated/tristate.conf ../scripts/kconfig/main/conf --silentoldconfig Kconfig && \
+		find include/generated -mindepth 1 ! -name 'autoconf.h' -delete; \
+	fi
+
+savedefconfig:
+	@$(MAKE) -C ../scripts/kconfig
+	@../scripts/kconfig/main/conf --savedefconfig=defconfig Kconfig
 
 limine_header: config.mk Makefile
 	@if [ ! -f include/limine/limine.h ]; then \
@@ -43,11 +111,12 @@ uacpi: config.mk Makefile
 
 $(UACPI_OUTFILE): $(UACPI_OBJ) FORCE
 	@needs_archive=0; \
-	has_debug=0; \
+	has_debug="n"; \
 	if [ -f "$(UACPI_OUTFILE)" ] && $(OBJDUMP) -h "$(UACPI_OUTFILE)" 2>/dev/null | grep -q '\.debug'; then \
-		has_debug=1; \
+		has_debug="y"; \
 	fi; \
-	if [ ! -f "$(UACPI_OUTFILE)" ] || [ "$(DEBUG)" != "$$has_debug" ]; then \
+	has_debug_cfg="n"; if [ "$(CONFIG_DEBUG)" = "y" ]; then has_debug_cfg="y"; fi; \
+	if [ ! -f "$(UACPI_OUTFILE)" ] || [ "$$has_debug_cfg" != "$$has_debug" ]; then \
 		needs_archive=1; \
 	else \
 		for obj in $(UACPI_OBJ); do \
@@ -60,7 +129,7 @@ $(UACPI_OUTFILE): $(UACPI_OBJ) FORCE
 	if [ $$needs_archive -eq 1 ]; then \
 		printf "  %-7s %s\n" "AR" "$(SUBDIR)/$(UACPI_OUTFILE)" && \
 		$(AR) rcs $(UACPI_OUTFILE) $(UACPI_OBJ) && \
-		if [ "$(DEBUG)" -eq 0 ]; then \
+		if [ "$(CONFIG_DEBUG)" != "y" ]; then \
 			printf "  %-7s %s\n" "STRIP" "$(SUBDIR)/$(UACPI_OUTFILE)" && \
 			$(STRIP) $(UACPI_STRIPFLAGS) $(UACPI_OUTFILE); \
 		fi; \
@@ -77,6 +146,10 @@ $(SUBDIRS): config.mk Makefile
 	@$(MAKE) -C $@
 
 kernel: config.mk Makefile linker.ld
+	@if [ ! -f .config ]; then \
+		printf "  %-7s %s\n" "ERROR" "No configuration file found, run 'make menuconfig' first" && \
+		exit 1; \
+	fi
 	@$(MAKE) limine_header
 	@$(MAKE) uacpi
 	@$(MAKE) $(SUBDIRS)
@@ -86,7 +159,8 @@ kernel: config.mk Makefile linker.ld
 	if [ -f "$(OUTFILE)" ] && $(OBJDUMP) -h "$(OUTFILE)" 2>/dev/null | grep -q '\.debug'; then \
 		has_debug=1; \
 	fi; \
-	if [ ! -f "$(OUTFILE)" ] || [ "$(DEBUG)" != "$$has_debug" ]; then \
+	has_debug_cfg=0; if [ "$(CONFIG_DEBUG)" = "y" ]; then has_debug_cfg=1; fi; \
+	if [ ! -f "$(OUTFILE)" ] || [ "$$has_debug_cfg" != "$$has_debug" ]; then \
 		needs_link=1; \
 	else \
 		for obj in $(OBJ); do \
@@ -99,15 +173,13 @@ kernel: config.mk Makefile linker.ld
 	if [ $$needs_link -eq 1 ]; then \
 		printf "  %-7s %s\n" "LD" "$(SUBDIR)/$(OUTFILE)" && \
 		$(LD) $(LDFLAGS) -o $(OUTFILE) $(OBJ) $(LIBS) && \
-		if [ "$(DEBUG)" -eq 0 ]; then \
+		if [ "$(CONFIG_DEBUG)" != "y" ]; then \
 			printf "  %-7s %s\n" "STRIP" "$(SUBDIR)/$(OUTFILE)" && \
 			$(STRIP) $(STRIPFLAGS) $(OUTFILE); \
 		fi; \
 	else \
 		printf "  %-7s %s\n" "INFO" "$(SUBDIR)/$(OUTFILE) is already up to date"; \
 	fi
-
-FORCE:
 
 clean:
 	@printf "  %-7s %s\n" "CLEAN" "$(SUBDIR)/$(OUTFILE)"
@@ -120,7 +192,11 @@ clean:
 	@rm -rf $(UACPI_BUILD)
 
 mrproper: clean
+	@printf "  %-7s %s\n" "CLEAN" "$(SUBDIR)/include/generated/ $(SUBDIR)/.config $(SUBDIR)/.config.old $(SUBDIR)/.config.cmd"
+	@rm -rf include/generated .config .config.old .config.cmd
 	@printf "  %-7s %s\n" "CLEAN" "include/limine/"
 	@rm -rf include/limine
 
-.PHONY: all limine_header uacpi $(SUBDIRS) kernel FORCE clean mrproper
+FORCE:
+
+.PHONY: all menuconfig allyesconfig allnoconfig alldefconfig defconfig oldconfig olddefconfig savedefconfig limine_header uacpi $(SUBDIRS) kernel clean mrproper FORCE
